# Zeabur 部署配置文件

# 应用名称
name = "ai-news-collector-mcp"

# 应用描述
description = "AI News Collector MCP Server with API and MCP support"

# 构建设置
[build]
# 构建命令
command = "npm run build"

# 启动命令
[start]
command = "dumb-init node dist/index.js"

# 环境变量配置
[env]
# 基础环境变量
NODE_ENV = "production"
LOG_LEVEL = "info"

# 服务配置
PORT = "3000"
API_PORT = "3001"

# 数据库配置
DATABASE_TYPE = "sqlite"
DATABASE_URL = "file:./data/ai_news.db"

# Redis配置
REDIS_HOST = "localhost"
REDIS_PORT = "6379"

# RSSHub配置
RSSHUB_URL = "http://124.221.80.250:5678"

# 安全配置
CORS_ORIGIN = "*"

# 端口暴露
[expose]
# 暴露API端口
port = 3001

# 健康检查
[health]
path = "/health"
interval = "30s"
timeout = "10s"
retries = 3

# 服务配置
[service]
# 自动重启
restart_policy = "always"

# 资源限制
[resources]
# 内存限制
memory = "512Mi"
# CPU限制
cpu = "0.5"

# 域名配置
[domain]
# 主域名
main = "ai-news-collector-mcp.zeabur.app"

# 构建缓存
[cache]
paths = [
  "node_modules",
  "dist"
]

# 持久化存储
[persistent]
paths = [
  "/app/data",
  "/app/logs"
]

# 日志配置
[logging]
# 日志级别
level = "info"
# 日志格式
format = "json"
# 日志保留天数
retention = "7"