name: Deploy to Zeabur

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Deploy to Zeabur
      uses: zeabur/action-deploy@v1
      with:
        # Zeabur API Token
        token: ${{ secrets.ZEABUR_TOKEN }}
        # 项目ID
        project_id: ${{ secrets.ZEABUR_PROJECT_ID }}
        # 应用名称
        app_name: "ai-news-collector-mcp"
        # 部署目录
        path: "."
        # 环境变量
        env: |
          NODE_ENV=production
          LOG_LEVEL=info
          PORT=3000
          API_PORT=3001
          DATABASE_TYPE=sqlite
          DATABASE_URL=file:./data/ai_news.db
          REDIS_HOST=localhost
          REDIS_PORT=6379
          RSSHUB_URL=http://124.221.80.250:5678
          CORS_ORIGIN=*
        # 健康检查路径
        health_check_path: "/health"